/*
 *
 * Explorer constants
 *
 */

export const DEFAULT_ACTION = 'app/Explorer/DEFAULT_ACTION';
export const SELECT_TCGROUPS_REQUEST = 'SELECT_TCGROUPS_REQUEST';
export const SELECT_TCGROUPS_SUCCESS = 'SELECT_TCGROUPS_SUCCESS';
export const SELECT_TCGROUPS_ERROR = 'SELECT_TCGROUPS_ERROR';
